/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_appsflyer_androidsampleapp_JniTest */

#ifndef _Included_com_appsflyer_androidsampleapp_JniTest
#define _Included_com_appsflyer_androidsampleapp_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_appsflyer_androidsampleapp_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_appsflyer_androidsampleapp_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     com_appsflyer_androidsampleapp_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_appsflyer_androidsampleapp_JniTest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
